name = "Puertas Juradas"
author = "JuanMaCozar"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa019f10fb53a8c7f1157d50ad325d34ca1750ea68728b8324f3f09d7df754ee"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
