name = "Puertas Juradas"
author = "JuanMaCozar"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ada3d27d950468f73a0ad52d35eb41b081a4e4ac88de024193ce7b86458390c8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
