name = "Puertas Juradas"
author = "JuanMaCozar"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a83c52db4b8662288c431873506c62b51a3d2d4d9199a8faa98067edc34ee2a1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
